### ISSUE TITLE
Outline button padding

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#11]
I noticed there is some padding inconsistency between the filled and Outline buttons. The Outline button style is slightly smaller, and has some custom CSS somewhere.

![Screenshot 2023-04-06 at 7 13 05 PM](https://user-images.githubusercontent.com/4193672/230437026-4338aad7-f13d-45a3-bf6f-dd467f0fc0f7.png)

This is the css. If you remove this padding rule, the buttons have the same size (as wanted).

```
.wp-block-button .wp-block-button__link.is-style-outline, 
.wp-block-button.is-style-outline>.wp-block-button__link {
    border: 2px solid;
    padding: 0.667em 1.333em;
```

I did not want to touch the code @preda-bogdan, you think you can take a look into this?

**Comment by preda-bogdan** [comment]
@JohnPixle This is coming from the core there is an issue here: https://github.com/WordPress/gutenberg/issues/34853

Removing this for me it looks a bit bigger because of the border. See the images below. Can you confirm that this is the correct behavior?

Here is using the core padding (as it is now and referenced in this issue):
![image](https://user-images.githubusercontent.com/23024731/230569846-b18722f2-85de-440a-a280-8e8b4bd74ec0.png)

Here is with the padding set the same as in `theme.json`:
![image](https://user-images.githubusercontent.com/23024731/230570036-c9a96530-d571-4605-9ec9-b1f17f99a8da.png)

**Comment by preda-bogdan** [comment]
@JohnPixle Ok, that seems good. I'll add this to `development` and link the changes. Thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle this is not happening on my end it uses the text color. Where is this happening for you?

**Comment by preda-bogdan** [comment]
@JohnPixle This should be resolved now and available on your design branch, we can close this once you confirm it is fixed.
