### ISSUE TITLE
Social Media icon color 

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#12]
@preda-bogdan I have another issue that I need help with whenever you can. I noticed that despite the fact that the colors of the social media icons are set to `ti-foreground` they do not inherit this value, and thus they do not change as the user changes style variations. There seems to be a dark inline color applied on them that stays persistent across style variations.

You can check this at the very first pattern on this page: https://fse-neve.vertisite.cloud/patterns/

![Screenshot 2023-04-07 at 11 46 41 AM](https://user-images.githubusercontent.com/4193672/230576293-e752c9e4-3244-4c75-8ad9-8ee4f80f20ea.png)

Thanks in advance!

**Comment by preda-bogdan** [comment]
@JohnPixle Here I've looked into the issue and the pattern is created with a defined color value.
The pattern should have `var(--wp--preset--color--ti-fg)`right now it has the hardcoded value from when it was added e.g. "#1F2023". I think this is an issue with how the core block is working and the fact that the block will save the value of the color instead of a reference to the variable used.

![image](https://user-images.githubusercontent.com/23024731/230605562-2029dcd8-8813-4847-860d-5265d39c7fa9.png)

If this will be part of the patterns we pre-made, we can change that when defining the patterns.
