### ISSUE TITLE
Add Templates

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#17]
@preda-bogdan I think we can start transferring / replacing some of the templates from the demo to the actual theme code.

I am starting with the Site Editor Templates.
You can copy them directly from the Demo, I am sharing the direct links with you below:

[Index](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postId=neve-fse%2F%2Findex&postType=wp_template&canvas=edit)

[Archive](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postId=neve-fse%2F%2Farchive&postType=wp_template&canvas=edit)

[Single Post (Default)](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postId=neve-fse%2F%2Fsingle&postType=wp_template&canvas=edit)

[Single Post 2 (Cover boxed)](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postType=wp_template&postId=neve-fse%2F%2Fsingle-post-hello-world&canvas=edit)

[Single Post 3 ( Cover)](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postType=wp_template&postId=neve-fse%2F%2Fsingle-post-how-to-choose-the-right-color-scheme-for-your-website&canvas=edit)

[Page](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postId=neve-fse%2F%2Fpage&postType=wp_template&canvas=edit)

[404](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postId=neve-fse%2F%2F404&postType=wp_template&canvas=edit)

[Search Results](https://fse-neve.vertisite.cloud/wp-admin/site-editor.php?postId=neve-fse%2F%2Fsearch&postType=wp_template&canvas=edit)

- For single post template, as you see we have three variations. How will these play out in the theme editor? I mean, how will the user be able to choose between these 3 different templates?
- For Homepage template, we’ll wait to create the patterns first, since what we have in homepage should also be included as a pattern.

Please let me know if you need any help!

**Comment by preda-bogdan** [comment]
@JohnPixle I've added all the templates and also replaced the Front Page with some patterns eg. the hero image and the icon box. For the single variations, I think we can have them as a full pattern under layouts, or/and add an additional category `Page Variations` where we only include full-page patterns.

What do you think?
You can check all these changes except the Single variations where I'm awaiting your input on the linked PR.

Let me know, thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle 
cc: @mghenciu 

Added a new category and the descriptions you provided and registered the Single variations under the new category.
![image](https://user-images.githubusercontent.com/23024731/233070681-e24f4059-8845-46cc-abb4-aa1cc5c5cdb6.png)

The changes are available on the linked PR.

Let me know if everything is in order now.

Thank you!

**Comment by mghenciu** [comment]
Looks good, @preda-bogdan  🔝 

From what I've discussed with @JohnPixle , **I think the Layouts for Archives should also be included there.**
For Single Pages (not posts) I am not 100% it makes sense.

___

Also, I wanted to ask @JohnPixle , for this Layouts having the Header & Footer in them - is expected, right?
I am asking based on the flow that a user would take in order to change the Single post template. In the curent flow, this would mean:
1. Go to current Single Post template
2. remove everything there
3. insert the Neve FSE Single Post Layout
4. Save & Publish the changes


The other flow for this would be:
1. Go to current Single Post template
2. remove **only the main group** (not the header and footer)
3. insert the Neve FSE Single Post Layout containing the Single Post template, but without footer and header
4. Save & Publish the changes

**Comment by preda-bogdan** [comment]
@mghenciu If the layouts for Archives are ready I can also add them. We can also have them without headers based on what you decide.

**Comment by mghenciu** [comment]
Sounds good, thank you for clarifying.

As a **Base** for Post Archives, we'll have the ones that are also available in Neve: List, Covers, Grid.
By Default, the **Grid Layout** is used, example here > https://fse-neve.vertisite.cloud/blog/

___
### Covers
Covers will look like this: 
![Screenshot 2023-04-19 at 17 01 07](https://user-images.githubusercontent.com/52494172/233099230-de04ebf3-99d8-4c44-97c3-5d69cc847217.png)
You can add it from this HTML File: [Covers.html.zip](https://github.com/Codeinwp/neve-fse/files/11273891/Covers.html.zip) or from the last Group on [this page](https://fse-neve.vertisite.cloud/loop-patterns/).

___
### List
And this is how the list would look:
![Screenshot 2023-04-19 at 17 03 43](https://user-images.githubusercontent.com/52494172/233100053-44aa8ecb-c730-438b-b554-c254800532dc.png)

HTML: 
[List.html.zip](https://github.com/Codeinwp/neve-fse/files/11273924/List.html.zip)


___
Additionally we may add other variants, like **Wide**, **Grid Boxed**, **List Boxed**.
Does this sounds good, @JohnPixle ?

**Comment by preda-bogdan** [comment]
@JohnPixle 
cc: @mghenciu 

Added the Cover and the List Archive Layouts, removed the header and footer from the variants so that the user can just replace the group.

For the archives, I've added the search group also as it is on the main Archive to the archive variants.

All the changes are on the linked PR.

**Comment by preda-bogdan** [comment]
@mghenciu the `template-blank` I think it is good to have as I see it is present on all our other FSE themes. I've removed the `single-cover-boxed`.

Let me know if there is anything else that is required from me and if we can proceed. Thank you!

**Comment by mghenciu** [comment]
Ok, thank you for claryfing.
I think we are good to go for the merge 🚀 

The only thing that we'll change later is the Screenshot, but that won't affect the functionality.
