### ISSUE TITLE
Form colors not adapting

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#18]
@preda-bogdan I noticed some issues with the Form styles, can you see if we can do something?

Below is the form at the bottom of this page: https://fse-neve.vertisite.cloud/blog/

![Screenshot 2023-04-10 at 3 19 33 PM](https://user-images.githubusercontent.com/4193672/230900505-3c285cf4-e0c7-4e56-9412-7a9eb8a959f7.png)

In the editor, the text color of the field is set to the foreground-alt (white-ish) but the field's border does not seem to inherit this value at the frontend. Can we have the field's border (and placeholder text) adapt to the Text color defined?

![Screenshot 2023-04-10 at 3 22 36 PM](https://user-images.githubusercontent.com/4193672/230900985-a57858d3-1ef4-48a3-b271-48008ab72953.png)

Let me know if I can help in any way

**Comment by preda-bogdan** [comment]
@JohnPixle Here I've made a small change on the PR with the templates so that the text color on the search input field respects the body font color so that when on dark backgrounds it will be visible. For the border color, there is a separate control for the block that handles that and is part of Gutenberg, there is no way to apply the same text color to the Placeholder for the input. The text color is applied to other form elements as expected, e.g. comments section, but the search block works in a different way.

Let me know if this makes things more clear and if you have other issues with regard to the form elements that I can help with.

Thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle I've changed the defaults to how they are set on Jaxon, let me know if this issue is resolved now. Thank you!
