### ISSUE TITLE
NeveFSE survey notice

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#32]
At some point soon, we can start exposing the Neve FSE survey with our users.
:sparkle: Here is the link to the final version of the survey: https://hi507076.typeform.com/neve-fse

### Dashboard notifications
Initially can simply add a survey link in the dashboard. This can be triggered on a condition, perhaps a few days after the user has the theme activated (let's say 2?). It can be a good indicator that they have spent enough time with it, in order to provide some meaningful insights. 

Text on notification: `We value your feedback! Join us in making Neve FSE even better by sharing your insights through a quick survey today! Take the Survey!`

![dashboard](https://github.com/Codeinwp/neve-fse/assets/4193672/bf7c3d45-752b-4297-831c-b9e612506b43)

Also, I think we should have a "dismiss" icon/link in case users want to remove the notification.

cc @HardeepAsrani @preda-bogdan  @selul 

___
### [Figma](https://www.figma.com/file/hYUMuIf40zwAM84YCzfim5/Neve-FSE?type=design&node-id=953-340&t=O7PmIQ7rlL8sBZPi-11)

**Comment by preda-bogdan** [comment]
@JohnPixle Yes, I think it can be added by next week and have a small Neve FSE release.
cc: @HardeepAsrani Do you have any thoughts on this?

**Comment by HardeepAsrani** [comment]
Looks good to me. Maybe we can have a delay of 3 or 7 days instead of just 2? Might be good to give user some time to explore and finding pain points before asking for feedback. What do you both think?

**Comment by mghenciu** [comment]
I think it depends, since some users may install the theme and use it actively in the first 2 days, while others can have it installed for 2 weeks without doing much with it.

In theory, **a 3 day delay should be ok**. And we can adjust it later, as Harshit also mentioned, depending on how many responses we get.


___
Alternatively, we can use a dismiss button (Maybe later | Skip for now), which will remind users about the message after some time. So for example if we show this after 3 days, and the user clicks Maybe later -> then we show the notice again after 1 week or so. But this may require more code logic/work, and I am not sure if it's worth investing.

<img width="1387" alt="image" src="https://github.com/Codeinwp/neve-fse/assets/52494172/5c7f1312-e5d2-4945-8c6d-53d27b7361f0">

**Comment by preda-bogdan** [comment]
@Codeinwp/design-team I added the notice on the linked PR, can you let me know if it is ok design-wise? I went with the initial suggestion.

**Comment by preda-bogdan** [comment]
I have updated the notice with the design that Mihai suggested. Let me know if you have any feedback. Thank you!

**Comment by preda-bogdan** [comment]
@JohnPixle Sorry, I did not push the latest changes, the build should be updated now.

**Comment by irinelenache** [comment]
@preda-bogdan Tested and everything works fine here, thank you 🚀 

@JohnPixle For updating options in cases like this one, you can just go to **websitename.com/wp-admin/options.php** and change the value from there https://vertis.d.pr/i/izi9Bn ✅
