### ISSUE TITLE
More control for each variation

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/neve-fse#5]
Hey @preda-bogdan

Ideally, we'd like some more control over the Typography of each Style Variation, especially font weight.

For example, for the Second Style, we want the H1-H6 weights to be bold (700).

Currently the[ style variation files](https://github.com/Codeinwp/neve-fse/blob/development/styles/s1-crayola.json) contain the color options and family definition. Would it be possible for you to add the part that controls the Heading styles?

I will be happy to adjust the values myself, but I am not quite sure how to write the json.

Let me know if you need any clarifications!

**Comment by preda-bogdan** [comment]
@JohnPixle It should be no problem, I will have a look and tag it back here. Do you have a list of what heading styles we want for each variation? For the ones that don't require one, we can have just the typography definition we have now.

**Comment by preda-bogdan** [comment]
@JohnPixle I've added the font-weight style for the first variation so that all headings will use the 700 weight.
You can use the same format to change other variations or you can let me know if you require any help and I will do them just provide me with a list of what you want the controls to be for each variation. 

You can use the development branch or just look at the linked commit for the changes.

Thank you!

**Comment by preda-bogdan** [comment]
Hey @JohnPixle, do you need any help here? What is the status of this?

**Comment by preda-bogdan** [comment]
Closing this as the changes are available on Development now.
