### ISSUE TITLE
Header section extends the Height when previewing Styles 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/neve-fse#73]
### Description

As seen in the video, the Hero section on the homepage extends its height when in Styles view.
<img width="1636" alt="Screenshot 2023-08-17 at 13 49 23" src="https://github.com/Codeinwp/neve-fse/assets/52494172/51a173f9-364b-4a1f-bd83-f2c442e1d8f2">

### Step-by-step reproduction instructions

1. Install Neve FSE 1.0.5
2. Open Editor on the Homepage
3. Open the Style Tab and switch styles

This may be cause by WP 6.3, so make sure to use that.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://github.com/Codeinwp/neve-fse/assets/52494172/09cabbc5-95db-4cb8-b093-b724f5c346f7

### Is the issue you are reporting a regression

No

**Comment by cristian-ungureanu** [comment]
@mghenciu The reason why those sections are growing is because they have a 50VH height. VH is the View height. 1vh is 1% of the height of the viewport. When previewing the style, the viewport gets to a height of 7120px and since those cover sections are relative to their viewport, they get bigger.

Here's what I can do:
1. Edit the template and replace `vh` with `vmin` unit. 1vmin is 1% of the viewport's smallest dimension, and 1vmax is 1% of the viewport's largest dimension. The problem is that the unit control used for setting the minimum height for a cover block does not have a `vmin` unit. It will work at the beginning, but if you change the unit, you can't get it back.
See here how the fix would look like: https://vertis.d.pr/v/gDVQxJ

2. Change the unit to something else that is not relative to the viewport size ( eg. 460px )

Let me know what you think.

cc @HardeepAsrani

**Comment by cristian-ungureanu** [comment]
@mghenciu 600px the page cover but what about the dark cta section at the end?

**Comment by mghenciu** [comment]
I would say **500px** should be ok for the bottom part. Since that part is secondary and it doesn't impact the first look on the users perception.
