### ISSUE TITLE
Feat: Inherit Font Family from Neve

### ISSUE THREAD

**Issue by preda-bogdan** [Codeinwp/neve-fse#9]
Inherit Font Families from Neve if previously set in Neve.
When the FSE theme is activated settings related to Typography should be inherited from Neve if present and applied to the default style.

**Comment by preda-bogdan** [comment]
@Codeinwp/design-team 

What do you guys think about using Responsive typography?

What I want to do is remap the sizes that we now have:
```
{
          "slug": "small",
          "size": "14px",
          "name": "Small"
        },
        {
          "slug": "normal",
          "size": "18px",
          "name": "Normal"
        },
        {
          "slug": "medium",
          "size": "24px",
          "name": "Medium"
        },
        {
          "slug": "large",
          "size": "28px",
          "name": "Large"
        },
        {
          "slug": "x-large",
          "size": "40px",
          "name": "Extra Large"
        },
        {
          "slug": "huge",
          "size": "64px",
          "name": "Huge"
        }
```

to instead be resized based on the normal font size, the normal font size will be computed based on a `root` multiplied by an `adaptive-ratio` that is tied to the `viewport-width`.
Instead of defining specific values for each size, the values will be automatically computed based on the `root` and the `scale` factor between sizes. We can use a `clamp` to fix the max and minimum values for each size.


Here is an example:
```yml
rootFontSize = 12
adaptiveRatio = 0.8
scale=1.4

# normalFontSize will computed as it follows:
normalFontSize = rootFontSize * 1px  + ( adaptiveRatio * 0.5vw )

# For a viewport of 1920px the 0.5vw is equal to (1920*0.5)/100 => 9.6px
normalFontSize = 12px + 7.68px => 19.68px

# We can further clamp this value between a min and a max

maxNormal = 18px
minNormal = maxNormal / 2  - min value will be half the max value


# Using this here is the final font size:

normalFontSizeClamp = clamp( 9px,  normalFontSize, 18px )

### Desktop: 1920
normalFontSizeClamp = 18px - the max size after clamp

### Tablet: 1180
normalFontSizeClamp = 16.72px

### Tablet: 820
normalFontSizeClamp = 15.28px

### Mobile: 375
normalFontSizeClamp = 13.5px

```

The other fonts will use the scale factor to be computed:
E.g. 
```yml
smallFontSize = normalFontSize / scale
mediumFomtSize = normalFontSize * scale
largeFontSize = mediumFontSize * scale
xLargeFontSize = largeFontSize * scale
hugeFontSize = xLargeFontSize * scale
```

Here are some images using this technique:
Mobile
![image](https://user-images.githubusercontent.com/23024731/230062055-b16aa595-9e24-488c-a793-cb16ab546b7e.png)

Tablet
![image](https://user-images.githubusercontent.com/23024731/230062245-d9e1a4fa-f589-450b-a89c-a86a85676358.png)

Desktop
![image](https://user-images.githubusercontent.com/23024731/230062368-d8f2515e-701e-49ba-bc1d-db902aa048ea.png)


I will also link a PR where I'm implementing the font migration from Neve for you to test this.

@Codeinwp/theme-dev Your feedback is welcome here.

**Comment by mghenciu** [comment]
Sounds like a good idea, Bogdan.

I think something about **Fluid Typography was rolled out with WP 6.1**, [mentioned here](https://fullsiteediting.com/lessons/theme-json-typography-options/#h-fluid-typography-with-gutenberg) and [here](https://github.com/WordPress/gutenberg/issues/24480). 
Another example is applied here, for the [Frost FSE theme](https://frostwp.com/styles/fluid-typography/).

Not sure if you are referring to exactly the same thing. But long term, I would keep Typography in sync with the Core approach - as hopefully soon they will add Font Sizes per device, and we should be ready for that.

**Comment by preda-bogdan** [comment]
@JohnPixle cc @mghenciu You can use the build from the PR to play around with the fluid typography and let me know if it works for you. The PR also inherits the font family, font size, line height, and weight from Neve if they've been set there. For the font family, we only import the family if it is already one of the fonts that the theme has available.

Let me know your thoughts.

**Comment by mghenciu** [comment]
Sorry in advance for the long comment :)

I've tested now, by doing this:
- created a instance with Neve
- imported the Architecture Gb demo
- installed Neve FSE fluid typography build.


**Overall looks good,** nice job Bogdan. Here are some side by side screens (**Neve FSE left** side and **Neve legacy on right side**):
### Desktop
![image](https://user-images.githubusercontent.com/52494172/230347421-d04d75a2-5319-4c06-a5af-62c937457958.png)
![image](https://user-images.githubusercontent.com/52494172/230348125-bf68fc1d-b52a-4e55-8dea-56eae211ddfe.png)
![image](https://user-images.githubusercontent.com/52494172/230348352-5149facd-d866-4dad-b79f-4125cdc69508.png)
 
Nothing major on Desktop, I would say, only this 2 small things (we can live with them): 
![Screenshot 2023-04-06 at 13 21 28](https://user-images.githubusercontent.com/52494172/230351006-6847560c-759f-4c8d-8372-d9f19ecf5552.png)


___
### Tablet
On Tablet it also looks ok, overall. But due to the limited space, the differences between font sizes are more visible. Ideally we should try to be in the same range when doing font-size inheritance. In this examples is visible that the Headings are much bigger in FSE: 
![Screenshot 2023-04-06 at 13 28 57](https://user-images.githubusercontent.com/52494172/230351916-f3417a21-5685-490c-b092-418e37ef9d2b.png)
![Screenshot 2023-04-06 at 13 29 42](https://user-images.githubusercontent.com/52494172/230351937-3533c461-4965-42a3-83ad-1d3212959702.png)

___
### Mobile
On Mobile same thing applies as on the Tablet. But overall nothing major, and probably looks worse when compared to the original demo; but in a normal context - the visual differences are not major:
 
![Screenshot 2023-04-06 at 13 33 22](https://user-images.githubusercontent.com/52494172/230352972-5c325c85-1629-451d-8272-bc42c770dcac.png)
![Screenshot 2023-04-06 at 13 34 14](https://user-images.githubusercontent.com/52494172/230352978-6586dd36-8c9d-4449-889e-845c2e0b2971.png)


___
Based on testing this demo side by side, I think we can also create a new issue and look into inheriting the Button border radius - if possible.
What do you think?

**Comment by preda-bogdan** [comment]
@mghenciu Thank you for taking the time to look over this. We can increase the `adaptiveRatio` and it will allow the font to have larger steps hence resulting in reaching maximum and minimum sizes much faster, I believe this can provide better approximations on smaller screens.

Inheriting the button border radius should not be a problem.

**Comment by preda-bogdan** [comment]
@JohnPixle great! I will merge this to development and sync the design branch with these changes. Then we can continue on that one. Thank you for taking the time to have a look at this. 🚀

**Comment by preda-bogdan** [comment]
The changes are now on `development`
